version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'laravel'
