name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          # Debugging: Print private key content
          cat private_key
          
          # Debugging: Print known_hosts content
          cat ~/.ssh/known_hosts
          
          # Debugging: Print current directory
          pwd
          
          # Debugging: Print list of files in the current directory
          ls -la
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Debugging: Print the current directory on the remote server
              pwd
              
              # Debugging: Print list of files in the current directory on the remote server
              ls -la
              
              cd /var/www/bleepus-backend &&
              git pull &&
              composer install --no-dev &&
              php artisan migrate --force &&
              php artisan optimize
          '
